openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
  description: PROJECT TOKO LAPTOP
servers:
  - url: http://127.0.0.1:5002
components:
  securitySchemes:
    bearertoken:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /test:
    get:
      responses:
        '200':
          description: OK
  /users1:
    post:
      summary: Login
      operationId: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: NOT FOUND
  /validated:
    get:
      summary: protected
      operationId: protected
      security:
        - bearertoken: []
      responses:
        '200':
          description: OK
  /users:
    post:
      description: 'tes' 
      security:
        - bearertoken: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                nama_lengkap:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /users/{id}:
    get:
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: sukses
        '400':
          description: gagal
    put:
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                nama_lengkap:
                  type: string
      responses:
        '200':
          description: sukses
        '400':
          description: coba lagi

    delete:
      description: hapus users
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi
  
  /kategori:
    get:
      description: mendapatkan semua kategori
      security:
        - bearertoken: []
      
      parameters:
        - name: keyword
          in: query
          description: search
          required: false
          schema:
            type: string
        - name: limit #nama sesuai dengan yang panggil di query
          in: query
          required: false
          schema:
            type: integer
            default: 5
        - in: query
          name: page
          required: false
          schema:
            type: integer
            default: 1

      responses:
        '200': 
          description: OK
        '400': 
          description: coba lagi
    
    post:
      description: membuat sebuah kategori
      security:
        - bearertoken: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                label:
                  type: string
      responses:
        '200':
          description: berhasil
        '400':
          description: coba lagi 
  /kategori/{id}:
    get:
      description: mencari kategori by id
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type : integer
      responses:
        '200':
          description: OK
        '400' : 
          description: Coba Lagi 
    delete:
      description: menghapus kategori by id
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: berhasil
        '400':
          description: coba lagi
    put:
      description: mengedit kategori by id
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                label:
                  type: string
      responses:
        '200':
          description: berhasil
        '400':
          description: coba lagi 
  /barang:
    get:
      description: Untuk mendapatkan semua jenis data barang
      security:
        - bearertoken: []
      parameters:
        - name: keyword
          description: search
          in: query
          required: false
          schema:
            type: string
            
        
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 5
        
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
      
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi 

    post:
      description: membuat barang
      security:
        - bearertoken: []
      requestBody:
        content:
          multipart/form-data:
            schema: 
              type: object
              properties:
                nama_barang :
                  type: string
                deskripsi :
                  type: string
                harga :
                  type: integer
                stok :
                  type: integer
                kategori_id :
                  type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Coba lagi 
  
  /barang/{id}:
    get:
      description: mencari barang berdasarkan id yang ada 
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200' : 
          description: OK
        '400' :
          description: coba lagi 
    
    put:
      description: mengedit barang dengan memasukkan id yang ada 
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nama_barang :
                  type: string
                deskripsi :
                  type: string
                harga :
                  type: integer
                stok :
                  type: integer
                kategori_id :
                  type: integer
      responses:
        '200' :
          description: OK
        '400' :
          description: Coba lagi 
    
    delete :
      description: menghapus barang dengan memasukkan id yang diperlukan 
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Coba lagi

  /keranjang:
    get:
      description: Untuk mendapatkan data dari keranjang 
      security:
        - bearertoken: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 5

        - name: page
          in: query
          schema:
            type: integer
            default : 1
          
      responses:
        '200':
          description: OK
        '400':
          description: Coba lagi

    post:
      description: untuk menambahkan keranjang
      security:
        - bearertoken: []
      requestBody:
        content:
          multipart/form-data:
           schema:
            type: object
            properties:
              barang_id :
                type: integer
              kuantitas :
                type: integer
      responses:
        '200':
          description: OK
        '400' :
          description: coba lagi 

  /keranjang/{id}:
    get:
      description: mendapatkan data keranjang dengan memasukkan id 
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path 
          required: true
          schema :
            type : integer
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi 

    put :
      description: mengedit data keranjang dengan memasukkan data by id 
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema :
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                barang_id:
                  type: integer
                kuantitas:
                  type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Coba lagi 
    
    delete :
      description: Menghapus data di keranjang dengan memasukkan id terlebih dahulu
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Coba lagi 
  
  /transaksi:
    get:
      description: untuk mendapatkan semua data yang ada di transaksi 
      security:
        - bearertoken: []
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 5
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: OK
        '400':
          description: Coba lagi
    
    post:
      description: untuk membuat data transaksi
      security:
        - bearertoken: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nama_lengkap:
                  type: string
                alamat:
                  type: string
                user_id:
                  type: string
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi 
  
  /transaksi/{id}:
    get:
      description: untuk mendapatkan data transaksi by id
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Coba lagi 
    
    put:
      description: mengedit data transaksi menggunakan id
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nama_lengkap:
                  type: string
                alamat:
                  type: string
                user_id:
                  type: integer
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi 
    delete:
      description: menghapus data di transaksi menggunakan id
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi
  
  /transaksi_detail:
    get:
      description: untuk mendapatkan semua data transaksi detail 
      security:
        - bearertoken: []
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 5
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: OK
        '400':
          description: Coba lagi 
  
    post:
      description: untuk menambah data transaksi detail
      security:
        - bearertoken: []
      requestBody:
        content:
          multipart/form-data:
            schema: 
              type: object
              properties:
                transaksi_id:
                  type: integer
                barang_id:
                  type: integer
                kuantitas:
                  type: integer
                harga:
                  type: integer
      responses:
        '200':
          description: OK
        '400':  
          description: Coba lagi 
              
  /transaksi_detail/{id}:
    get:
      description: mendapatkan transaksi detail dengan menggunakan id
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi 
    
    put:
      description: untuk mengedit data transaksi detail menggunakan id
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                transaksi_id:
                  type: integer
                barang_id:
                  type: integer
                kuantitas: 
                  type: integer
                harga:
                  type: integer
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi 
    
    delete:
      description: untuk menghapus data menggunakan id
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi 
  
  /cobasqlsendiri:
    get:
      description: untuk mendapatkan data sql join sendiri
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi 
          
  /upload:
    post:
      description: untuk melakukan upload gambar
      security:
        - bearertoken: []
      requestBody:
        content:
         multipart/form-data:
          schema:
            type: object
            properties:
              file:
                type: string
                format: binary
          encoding:
            profileImage: 
              contentType: image/jpg
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi

  /gambar/{id}:
    post:
      description: untuk melakukan edit pada suatu gambar melalui id
      security:
        - bearertoken: []
      parameters:
        - name: id
          in: path 
          required: true
          schema:
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: base64
            encoding:
              profileImage:
                contentType: image/jpg.
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi

    delete:
      description: untuk menghapus gambar berdasarkan id nya  
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '400':
          description: coba lagi

  /coba_transaksi:
    post:
      description: coba aja
      security:
        - bearertoken: []
      requestBody:
        content:
          multipart/form-data:
            encoding:
              id_keranjang:
                explode: true
            schema:
              type: object
              properties:
                id_keranjang:
                  type: array
                  items:
                    type: integer
                nama_lengkap:
                  type: string
                alamat:
                  type: string        
      responses:
        '200':
          description: OK
        '400':
          description: Coba lagi
                      
                
